import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { getAreaDashboard, type DashboardResponse } from '@/lib/api';

export function ISOAreaDetailPage() {
  const { slug: id = '' } = useParams();
  const [dashboard, setDashboard] = useState<DashboardResponse | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { getAreaDashboard(id).then(setDashboard).catch(value => setError(value instanceof Error ? value.message : 'Unable to load ISO area detail.')); }, [id]);
  if (error) return <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>;
  if (!dashboard) return <p className="text-sm text-muted-foreground">Loading ISO area...</p>;
  const area = dashboard.areas[0];
  if (!area) return <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">No reporting data available for this ISO area.</CardContent></Card>;
  return <div className="flex flex-col gap-6"><Link to="/iso-areas" className="text-sm text-muted-foreground hover:text-foreground">← ISO Areas</Link><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">ISO Area</p><h2 className="mt-1 text-xl font-semibold">{area.name}</h2><p className="mt-1 text-sm text-muted-foreground">{dashboard.period?.label}</p></div><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Completion</p><p className="mt-1 text-2xl font-semibold">{area.completionPercentage == null ? 'Not enough data' : `${area.completionPercentage}%`}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Total Metrics</p><p className="mt-1 text-2xl font-semibold">{area.totalMetrics}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Approved</p><p className="mt-1 text-2xl font-semibold">{area.statusCounts.approved}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Issues</p><p className="mt-1 text-2xl font-semibold">{area.statusCounts.attention}</p></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">Metrics</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-border bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Metric</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Result</th><th className="px-4 py-3">PIC</th></tr></thead><tbody>{area.metrics?.map(metric => <tr key={metric.id} className="border-b border-border"><td className="px-4 py-3"><Link className="font-medium hover:text-primary" to={`/metrics/${metric.id}`}>{metric.name}</Link></td><td className="px-4 py-3"><Badge variant={metric.status === 'Approved' ? 'success' : metric.status === 'Missing' ? 'warning' : 'info'}>{metric.status}</Badge></td><td className="px-4 py-3 tabular-nums">{metric.result == null ? 'Not calculated' : metric.result.toLocaleString(undefined, { maximumFractionDigits: 2 })}</td><td className="px-4 py-3 text-muted-foreground">{metric.pic}</td></tr>)}{!area.metrics?.length && <tr><td colSpan={4} className="px-4 py-8 text-center text-muted-foreground">No metrics configured in this area.</td></tr>}</tbody></table></div></CardContent></Card></div>;
}
