import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { getArea, getAreas, type ConfigurationArea } from '@/lib/api';

export function ISOConfigurationPage() {
  const [areas, setAreas] = useState<Array<Omit<ConfigurationArea, 'metrics'> & { _count: { metrics: number } }>>([]);
  const [selected, setSelected] = useState<ConfigurationArea | null>(null);
  const [error, setError] = useState('');

  useEffect(() => { getAreas().then(setAreas).catch(value => setError(value instanceof Error ? value.message : 'Unable to load areas.')); }, []);
  async function selectArea(id: string) {
    try { setSelected(await getArea(id)); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to load configuration.'); }
  }

  return <div className="flex flex-col gap-6"><div><h2 className="text-lg font-semibold">ISO Configuration</h2><p className="mt-1 text-sm text-muted-foreground">Browse the active configuration imported from the approved workbook.</p></div>{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="grid grid-cols-1 gap-6 lg:grid-cols-[260px_1fr]"><Card><CardHeader><CardTitle className="text-base">ISO Areas</CardTitle></CardHeader><CardContent className="flex flex-col gap-1 p-2">{areas.length === 0 && !error && <p className="p-3 text-sm text-muted-foreground">No imported areas yet.</p>}{areas.map(area => <button key={area.id} type="button" onClick={() => selectArea(area.id)} className={`flex items-center justify-between rounded-md px-3 py-2 text-left text-sm ${selected?.id === area.id ? 'bg-primary/10 font-medium text-primary' : 'text-muted-foreground hover:bg-accent hover:text-foreground'}`}><span className="truncate">{area.areaNumber}. {area.name}</span><span className="ml-2 text-xs">{area._count.metrics}</span></button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">{selected ? `${selected.areaNumber}. ${selected.name}` : 'Selected ISO Area'}</CardTitle></CardHeader><CardContent>{!selected ? <p className="text-sm text-muted-foreground">Select an area to inspect its metrics and configuration.</p> : <div className="flex flex-col gap-3">{selected.metrics.map(metric => <details key={metric.id} className="rounded-md border border-border"><summary className="cursor-pointer list-none px-4 py-3"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{metric.metricNumber}. {metric.name}</span><Badge variant="outline">{metric.metricType}</Badge></div></summary><div className="grid gap-4 border-t border-border px-4 py-4 text-sm md:grid-cols-2"><div><p className="text-xs text-muted-foreground">Data attributes</p>{metric.attributes.length ? <ul className="mt-2 list-disc pl-4">{metric.attributes.map(attribute => <li key={attribute.id}>{attribute.name} <span className="text-xs text-muted-foreground">({attribute.dataType})</span></li>)}</ul> : <p className="mt-2 text-muted-foreground">No attributes configured.</p>}</div><div className="space-y-3"><div><p className="text-xs text-muted-foreground">Formula</p><p className="mt-1">{metric.formulas[0]?.formula ?? metric.formulaDescription ?? 'No formula configured.'}</p></div><div><p className="text-xs text-muted-foreground">PIC / Division</p><p className="mt-1">{metric.pics.length ? metric.pics.map(pic => `${pic.picName} (${pic.picYear}${pic.division ? `, ${pic.division.code}` : ''})`).join(', ') : 'No PIC configured.'}</p></div></div></div></details>)}</div>}</CardContent></Card></div></div>;
}
