import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { getAreas, getDivisions, getReportingPeriods, type ReportingPeriod } from '@/lib/api';

export function ReportsPage() {
  const navigate = useNavigate();
  const [periods, setPeriods] = useState<ReportingPeriod[]>([]);
  const [areas, setAreas] = useState<Array<{ id: string; name: string }>>([]);
  const [divisions, setDivisions] = useState<Array<{ id: string; code: string }>>([]);
  const [filters, setFilters] = useState({ year: 2026, period: 'Annual', isoAreaId: '', divisionId: '' });
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([getReportingPeriods(), getAreas(), getDivisions()]).then(([loadedPeriods, loadedAreas, loadedDivisions]) => { setPeriods(loadedPeriods); setAreas(loadedAreas); setDivisions(loadedDivisions); if (loadedPeriods[0]) setFilters(current => ({ ...current, year: loadedPeriods.find(item => item.status === 'Open')?.year ?? loadedPeriods[0].year })); }).catch(value => setError(value instanceof Error ? value.message : 'Unable to load report filters.')); }, []);
  function update(key: keyof typeof filters, value: string) { setFilters(current => ({ ...current, [key]: key === 'year' ? Number(value) : value })); }
  return <div className="flex flex-col gap-6"><div><h2 className="text-lg font-semibold">ISO 30414 Reports</h2><p className="mt-1 text-sm text-muted-foreground">Generate document reports from approved metric data only.</p></div>{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<Card className="max-w-3xl"><CardHeader><CardTitle className="text-base">Create New Report</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Reporting year<select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={filters.year} onChange={event => update('year', event.target.value)}>{[...new Set(periods.map(item => item.year))].map(year => <option key={year}>{year}</option>)}</select></label><label className="text-sm font-medium">Reporting period<select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={filters.period} onChange={event => update('period', event.target.value)}><option>Annual</option><option>Quarterly</option><option>SemiAnnual</option></select></label><label className="text-sm font-medium">ISO area<select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={filters.isoAreaId} onChange={event => update('isoAreaId', event.target.value)}><option value="">All ISO Areas</option>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label className="text-sm font-medium">Division<select className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" value={filters.divisionId} onChange={event => update('divisionId', event.target.value)}><option value="">All Divisions</option>{divisions.map(division => <option key={division.id} value={division.id}>{division.code}</option>)}</select></label><div className="md:col-span-2"><p className="text-xs text-muted-foreground">Report status</p><p className="mt-1 text-sm font-medium">Approved Data Only</p></div><Button className="md:col-span-2" onClick={() => navigate(`/reports/preview?year=${filters.year}&period=${filters.period}${filters.isoAreaId ? `&isoAreaId=${filters.isoAreaId}` : ''}${filters.divisionId ? `&divisionId=${filters.divisionId}` : ''}`)}>Preview Approved Report</Button></CardContent></Card></div>;
}
