import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getReports } from '@/lib/api';

export function ReportHistoryPage() {
  const [reports, setReports] = useState<Awaited<ReturnType<typeof getReports>>>([]);
  const [error, setError] = useState('');
  useEffect(() => { getReports().then(setReports).catch(value => setError(value instanceof Error ? value.message : 'Unable to load report history.')); }, []);
  return <div className="flex flex-col gap-6"><div><h2 className="text-lg font-semibold">Report History</h2><p className="mt-1 text-sm text-muted-foreground">Previously generated report versions and files.</p></div>{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<Card><CardHeader><CardTitle className="text-base">Generated Reports</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Report</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Generated</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{reports.map(report => <tr key={report.id} className="border-b border-border"><td className="px-4 py-3 font-medium">{report.name}</td><td className="px-4 py-3">{report.reportingPeriod.label}</td><td className="px-4 py-3">v{report.version}</td><td className="px-4 py-3 text-muted-foreground">{new Date(report.createdAt).toLocaleString()}</td><td className="px-4 py-3">{report.status}</td><td className="px-4 py-3"><div className="flex gap-3"><Link className="text-primary hover:underline" to={`/reports/preview?id=${report.id}`}>View</Link>{report.files.some(file => file.format === 'PDF') && <a className="text-primary hover:underline" href={`/api/reports/${report.id}/download/PDF`}>PDF</a>}{report.files.some(file => file.format === 'EXCEL') && <a className="text-primary hover:underline" href={`/api/reports/${report.id}/download/EXCEL`}>Excel</a>}</div></td></tr>)}{reports.length === 0 && <tr><td colSpan={6} className="px-4 py-10 text-center text-sm text-muted-foreground">No reports generated yet.</td></tr>}</tbody></table></CardContent></Card></div>;
}
