import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { getReviewSummary, getReviews } from '@/lib/api';

export function ReviewQueuePage() {
  const [rows, setRows] = useState<Awaited<ReturnType<typeof getReviews>>>([]);
  const [summary, setSummary] = useState<{ pendingReview: number; approvedThisMonth: number; revisionRequired: number; rejected: number } | null>(null);
  const [status, setStatus] = useState('UnderReview');
  const [error, setError] = useState('');
  const load = () => Promise.all([getReviews({ status }), getReviewSummary()]).then(([loadedRows, loadedSummary]) => { setRows(loadedRows); setSummary(loadedSummary); }).catch(value => setError(value instanceof Error ? value.message : 'Unable to load review queue.'));
  useEffect(() => { void load(); }, [status]);
  return <div className="flex flex-col gap-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-semibold">Review Queue</h2><p className="mt-1 text-sm text-muted-foreground">Review submissions using server-enforced workflow rules.</p></div><select aria-label="Review status" className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={status} onChange={event => setStatus(event.target.value)}><option>UnderReview</option><option>Submitted</option><option>NeedsRevision</option><option>Approved</option><option>Rejected</option></select></div>{error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Pending Review', summary?.pendingReview], ['Approved This Month', summary?.approvedThisMonth], ['Revision Required', summary?.revisionRequired], ['Rejected', summary?.rejected]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value == null ? '...' : String(value)}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Submissions</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Metric</th><th className="px-4 py-3">ISO Area</th><th className="px-4 py-3">PIC</th><th className="px-4 py-3">Period</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-border"><td className="px-4 py-3 font-medium">{row.metric.name}</td><td className="px-4 py-3">{row.metric.isoArea.name}</td><td className="px-4 py-3">{row.submittedBy?.fullName ?? row.metric.pics[0]?.picName ?? 'Unassigned'}</td><td className="px-4 py-3">{row.reportingPeriod.label}</td><td className="px-4 py-3 text-muted-foreground">{row.submittedAt ? new Date(row.submittedAt).toLocaleDateString() : 'Not submitted'}</td><td className="px-4 py-3"><Badge variant={row.status === 'Approved' ? 'success' : row.status === 'Rejected' ? 'destructive' : 'warning'}>{row.status}</Badge></td><td className="px-4 py-3"><Link className="font-medium text-primary hover:underline" to={`/review/${row.id}`}>Review</Link></td></tr>)}{rows.length === 0 && <tr><td colSpan={7} className="px-4 py-10 text-center text-sm text-muted-foreground">No submissions in this queue.</td></tr>}</tbody></table></CardContent></Card></div>;
}
